// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolveDatabaseUrl } from "./src/lib/db-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Same connection this app's runtime (src/lib/prisma.ts) actually uses,
    // checked first, before any other Postgres integration's vars.
    url: resolveDatabaseUrl(),
  },
});
